### ISSUE TITLE
Dark mode support

### ISSUE THREAD

**Issue by th0mk** [gowon-bot/gowon.ca#2]
Would be nice if it could support dark mode.

An example of CSS for dark mode is:

```css        
@media (prefers-color-scheme: light) {
    body, a {
        color: #555;
    }
}

@media (prefers-color-scheme: dark) {
    body, a {
        background-color: black;
        color: #ddd;
    }
}
```
